version : "3"
services : 
  postgres:
    image : "postgres:alpine"
    container_name: postgres
    ports : 
     - "5432:5432"
    environment: 
      POSTGRES_PASSWORD : 1234
      POSTGRES_DB : cooper

  backend:
    build: "./backend"
    container_name: backend
    volumes: 
      - ./backend:/home/node/app
    ports:
      - "3002:3000"
    network_mode: bridge
    depends_on:
      - postgres

  frontend : 
    image : "nginx:alpine"
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "3001:80"
    depends_on:
      - postgres
      - backend
    
