version : "3"
services : 
  
  postgres:
    image : "postgres:alpine"
    container_name: postgres
    ports : 
     - "5432:5432"
    environment: 
      POSTGRES_PASSWORD : 1234
      POSTGRES_DB : cooper

  frontend : 
    image : "node:alpine"
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3001:3000"
    command:
      - cd frontend
      - npm install
      - npm start
    
  backend:
    image: node:alpine
    container_name: backend
    working_dir: /backend
    volumes: 
      - ./backend:/backend
    ports:
      - "3002:3000"
    command: "npm install"  
  