# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Desafio Coopersystem Heygon GirFlow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  postgres:

    runs-on: ubuntu-latest
    container: "postgres:alpine"
    
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD : 1234
          POSTGRES_DB : cooper
          
        environment: 
          POSTGRES_PASSWORD : 1234
          POSTGRES_DB : cooper

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        run: node client.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD : 1234
          POSTGRES_DB : cooper




  backend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd backend
    - run: yarn install
    - run: yarn start

  frontend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd backend
    - run: yarn install
    - run: yarn start
